@polwart_backend_HostAddress = http://localhost:5019

POST {{polwart_backend_HostAddress}}/map/connect
Accept: application/json

###

PATCH {{polwart_backend_HostAddress}}/map/patch
Accept: application/json

###
