// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace polwart_backend.Models;

public partial class Chat
{
    public int Id { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual ICollection<Space> SpaceChatAdmins { get; set; } = new List<Space>();

    public virtual ICollection<Space> SpaceChatCommons { get; set; } = new List<Space>();
}