// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace polwart_backend.Models;

public partial class ChatMessage
{
    public long Id { get; set; }

    public int ChatId { get; set; }

    public int UserId { get; set; }

    public string Text { get; set; }

    public DateTime Time { get; set; }

    public int? Tag { get; set; }

    public virtual Chat Chat { get; set; }

    public virtual User User { get; set; }
}