// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace polwart_backend.Models;

public partial class History
{
    public int Id { get; set; }

    public List<int> FramesId { get; set; }

    public virtual ICollection<Space> Spaces { get; set; } = new List<Space>();
}