// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace polwart_backend.Models;

public partial class SpaceArchived
{
    public int Id { get; set; }

    public string Layers { get; set; }

    public string Countries { get; set; }

    public string FixationTime { get; set; }
}