// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace polwart_backend.Models;

public partial class Space
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int OwnerId { get; set; }

    public string Password { get; set; }

    public string Layers { get; set; }

    public string Faq { get; set; }

    public string Countries { get; set; }

    public string Events { get; set; }

    public string Entities { get; set; }

    public int HistoryId { get; set; }

    public int ChatCommonId { get; set; }

    public int ChatAdminId { get; set; }

    public virtual Chat ChatAdmin { get; set; }

    public virtual Chat ChatCommon { get; set; }

    public virtual History History { get; set; }

    public virtual User Owner { get; set; }
}